export default [
    { label: "Indicação de amigos", value: "Indicação de amigos" },
    { label: "Balcão", value: "Balcão" },
    { label: "E-mail marketing", value: "E-mail marketing" },
    { label: "Facebook", value: "Facebook" },
    { label: "Folder e panfletos", value: "Folder e panfletos" },
    { label: "Fomulário web site", value: "Fomulário web site" },
    { label: "Instagram", value: "Instagram" },
    { label: "Outdoor e placas", value: "Outdoor e placas" },
    { label: "Rádio", value: "Rádio" },
    { label: "Sms Marketing", value: "Sms Marketing" },
    { label: "Telemarketing", value: "Telemarketing" },
    { label: "Televisão", value: "Televisão" },
    { label: "Twitter", value: "Twitter" },
    { label: "Visita de corretor", value: "Visita de corretor" },
    { label: "conect.app.br", value: "conect.app.br" },
    { label: "Mala direta - carta", value: "Mala direta - carta" },
    { label: "Whatsapp", value: "Whatsapp" },
    { label: "Retenção", value: "Retenção" },
    { label: "Divulgação", value: "Divulgação" },
    { label: "Google", value: "Google" },
    { label: "Jornal", value: "Jornal" },
    { label: "Revista", value: "Revista" },
    { label: "Receptivo", value: "Receptivo" },
    { label: "Abordagem externa", value: "Abordagem externa" },
    { label: "Panfletagem", value: "Panfletagem" },
    { label: "Indicação parceria", value: "Indicação parceria" },
]