export default [
    { label: "NORMAL", value: "NORMAL" },
    { label: "CARTÃO COM SAQUE", value: "CARTÃO COM SAQUE" },
    { label: "PORTABILIDADE", value: "PORTABILIDADE" },
    { label: "NOVO", value: "NOVO" },
    { label: "REFIN", value: "REFIN" },
    { label: "REFIN REVISIONADO", value: "REFIN REVISIONADO" },
    { label: "DIGITAL", value: "DIGITAL" },
    { label: "SAQUE COMPLEMENTAR", value: "SAQUE COMPLEMENTAR" },
    { label: "FLEX 1 DIGITAL", value: "FLEX 1 DIGITAL" },
    { label: "FLEX 2 DIGITAL", value: "FLEX 2 DIGITAL" },
    { label: "FLEX 3 DIGITAL", value: "FLEX 3 DIGITAL" },
    { label: "FLEX 4 DIGITAL", value: "FLEX 4 DIGITAL" },
    { label: "FLEX 5 DIGITAL", value: "FLEX 5 DIGITAL" },
    { label: "FLEX 6 DIGITAL", value: "FLEX 6 DIGITAL" },
    { label: "FLEX 7 DIGITAL", value: "FLEX 7 DIGITAL" },
    { label: "FLEX 1 NORMAL", value: "FLEX 1 NORMAL" },
    { label: "FLEX 2 NORMAL", value: "FLEX 2 NORMAL" },
    { label: "FLEX 3 NORMAL", value: "FLEX 3 NORMAL" },
    { label: "FLEX 4 NORMAL", value: "FLEX 4 NORMAL" },
    { label: "FLEX 5 NORMAL", value: "FLEX 5 NORMAL" },
    { label: "FLEX 6 NORMAL", value: "FLEX 6 NORMAL" },
    { label: "FLEX 7 NORMAL", value: "FLEX 7 NORMAL" },
    { label: "INVALIDEZ 59ANOS E 11MESES DIGITAL", value: "INVALIDEZ 59ANOS E 11MESES DIGITAL" },
    { label: "INVALIDEZ 59ANOS E 11MESES NORMAL", value: "INVALIDEZ 59ANOS E 11MESES NORMAL" },
    { label: "INVALIDEZ SEM CARÊNCIA TX 2,08", value: "INVALIDEZ SEM CARÊNCIA TX 2,08" },
    { label: "NORMAL SEM CARÊNCIA TX 2,08", value: "NORMAL SEM CARÊNCIA TX 2,08" },
    { label: "NORMAL TX 1,89%", value: "NORMAL TX 1,89%" },
    { label: "NORMAL TX 1,77%", value: "NORMAL TX 1,77%" },
    { label: "NORMAL TX 1,65%", value: "NORMAL TX 1,65%" },
    { label: "NORMAL SEM CARÊNCIA", value: "NORMAL SEM CARÊNCIA" },
    { label: "ESPECIAL", value: "ESPECIAL" },
    { label: "ESPECIAL 4 TX 1,82%", value: "ESPECIAL 4 TX 1,82%" },
    { label: "ESPECIAL 5 TX 1,72%", value: "ESPECIAL 5 TX 1,72%" },
    { label: "ESPECIAL 6 TX 1,65%", value: "ESPECIAL 6 TX 1,65%" },
    { label: "ESPECIAL 7 TX 1,60%", value: "ESPECIAL 7 TX 1,60%" },
    { label: "ESPECIAL 8 TX 1,55%", value: "ESPECIAL 8 TX 1,55%" },
    { label: "ESPECIAL 9 TX 1,50%", value: "ESPECIAL 9 TX 1,50%" },
    { label: "ESPECIAL 10 TX 1,45%", value: "ESPECIAL 10 TX 1,45%" },
    { label: "ESPECIAL 11 TX 1,40%", value: "ESPECIAL 11 TX 1,40%" },
    { label: "ESPECIAL 12 TX 1,30%", value: "ESPECIAL 12 TX 1,30%" },
    { label: "ESPECIAL 3 TX 1,92%", value: "ESPECIAL 3 TX 1,92%" },
    { label: "ESPECIAL TX 2,05%", value: "ESPECIAL TX 2,05%" },
    { label: "ESPECIAL 2 TX 1,97%", value: "ESPECIAL 2 TX 1,97%" },
    { label: "CARTÃO COM SAQUE C/SEGURO PRESTAMISTA", value: "CARTÃO COM SAQUE C/SEGURO PRESTAMISTA" },
    { label: "CARTÃO COM SAQUE C/SEGURO", value: "CARTÃO COM SAQUE C/SEGURO" },
    { label: "CARTÃO COM SAQUE COMPLEMENTAR", value: "CARTÃO COM SAQUE COMPLEMENTAR" },
    { label: "CARTÃO COM SAQUE COMPLEMENTAR C/SEGURO", value: "CARTÃO COM SAQUE COMPLEMENTAR C/SEGURO" },
    { label: "NORMAL VALOR MINI 300,00 A 999,99 43 A 48X", value: "NORMAL VALOR MINI 300,00 A 999,99 43 A 48X" },
    { label: "NORMAL CAREN 90DIAS", value: "NORMAL VALOR MINI 300,00 A 999,99 43 A 48X" },
    { label: "FLEX 1", value: "FLEX 1" },
    { label: "FLEX 2", value: "FLEX 2" },
    { label: "ESPECIAL 1", value: "ESPECIAL 1" },
    { label: "ESPECIAL 2", value: "ESPECIAL 2" },
    { label: "DIFERENCIADA 1", value: "DIFERENCIADA 1" },
    { label: "DIFERENCIADA 2", value: "DIFERENCIADA 2" },

    
]